
version: 2

models:

  - name: ent_apartment_complex
    description: >
      Entity table for apartment complexes. This currently includes counts of how many different taxpayer
      names have showed up for the apt complex, as well as how many complaints the building has had.

      Intended to be useful for identifying "problem" apartment complexes.

  - name: ent_taxpayer
    description: >
      Entity table for taxypayers. This currently includes counts of how many properties a taxpayer
      has paid taxes on, and how many properties the taxpayer address for this taxpayer shows up for.

      Intended to be useful for identifying big landlords.

  - name: stg_apartment_complex
    description: >
      Apartment complexes. Since this project is concerned with residential landlords, this is an
      important table, more so than condos or commercial buildings.

      The stg_parcel table doesn't have have an address. An apartment complex seems to have the same major_minor
      identifier as the parcel it sits on.

  - name: stg_parcel
    description: >
      PK is major_minor. Information about parcels.

      Important note: parcels don't have an address. You need to look in stg_apartment_complex or other
      files for specific types of parcels, to get addresses. This means this is a useful table to join to,
      in order to get attributes of a parcel, but it's often not a useful starting point.

  # - name: stg_parcel_address
  #   description: >
  #     Mapping of addresses to parcels.

  #     Parcels don't have an address. An apartment complex seems to have the same major_minor
  #     identifier as the parcel it sits on.

  - name: stg_real_property_account
    description: >
      "real" (eReal?) property accounts. Grain of this table is (acct_nbr, bill_yr, levy_code).

      Taxpayer info can be clues to ownership, but this data is very messy and complicated to
      work through. The names that show up in taxpayer_name can be LLC names, LCC agents,
      management companies, or direct owners. The addresses for taxpayers vary also.

      A taxpayer entity has multiple tax accounts, one per parcel they pay tax on.
      Rhere is no unique identifier in this data for a given person or company. This would need
      to be derived/reconciled downstream.

      Adjustments to taxpayer information could be handled by using a correction table of
      (major_minor, taxpayer_name, fixed_name) fields.

      The most recent files from KCDA have the TaxpayerName field removed, so we merge in older files
      to get those names. TODO: the names are also present in other current files in the dataset,
      try to use those instead.

sources:
  - name: src
    schema: public
    tables:
      - name: raw_apartment_complex
      - name: raw_commercial_building
      - name: raw_complaints
      - name: raw_condo_complex
      - name: raw_parcel
      - name: raw_real_property_account
      - name: raw_real_property_account_2022_07_06
      - name: raw_residential_building
      - name: raw_vacant_lot
  - name: pre
    description: data preprocessed from raw
    schema: public
    tables:
      - name: pre_apartment_complex_address
      - name: pre_corporations
      - name: pre_real_property_account_address
