table_keys:
  apartment_raw:
    path: 'raw/Apartment Complex/EXTR_AptComplex.csv'
    table_name: 'king_county_apartment_complexes_raw'
  commercial_raw:
    path: 'raw/Commercial Building/EXTR_CommBldg.csv'
    commercial_raw_feature_path: 'commercial_buildings/EXTR_CommBldgFeature.csv'
    commercial_raw_section_path: 'commercial_buildings/EXTR_CommBldgSection.csv'
    table_name: 'king_county_commercial_units_raw'
  condo_raw:
    path: 'raw/Condo Complex and Units/EXTR_CondoComplex.csv'
    condo_raw_unit_path: 'condos_complexes/EXTR_CondoUnit2.csv'
    table_name: 'king_county_condos_raw'
  residential_raw:
    path: 'raw/Residential Building/EXTR_ResBldg.csv'
    table_name: 'king_county_residential_raw'
  base_raw:
    legal_dscriptions_path: 'property_legal_descriptions.csv'
    path: 'raw/EXTR_Parcel.csv'
    table_name: 'king_county_parcel_raw'
  base_raw_tax:
    path: 'raw/EXTR_RPAcct_220706.csv'
    table_name: 'king_county_parcel_raw_tax'
