data_path: ../../data/
user: postgres
user_pw: 'v5UtGtw06T%nBqW'
table_user: king_county_connect
table_pw: '15EiidZabIx3SFi'
database_name: king_county_data_raw
hostname: localhost
table_keys:
  apartment:
    raw_path: 'apartment_complex/EXTR_ApartCom.csv'
    table_name: 'king_county_apartment_complexes_raw'
  commercial:
    raw_path: 'commercial_buildings/EXTR_CommBldg.csv'
    commercial_raw_feature_path: 'commercial_buildings/EXTR_CommBldgFeature.csv'
    commercial_raw_section_path: 'commercial_buildings/EXTR_CommBldgSection.csv'
    table_name: 'king_county_commercial_units_raw'
  condo:
    raw_path: 'condos_complexes/EXTR_CondoComplex.csv'
    condo_raw_unit_path: 'condos_complexes/EXTR_CondoUnit2.csv'
    table_name: 'king_county_condos_raw'
  residential:
    raw_path: 'residential_buildings/EXTR_ResBldg.csv'
    table_name: 'king_county_residential_raw'
  base:
    legal_dscriptions_path: 'property_legal_descriptions.csv'
    raw_path: 'EXTR_Parcel.csv'
    table_name: 'king_county_parcel_raw'
  base_tax:
    raw_path: 'EXTR_RPAcct_220706.csv'
    table_name: 'king_county_parcel_raw_tax'